# version: "8.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true # overrides dockerfile environment variable
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"